on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: swift run -v
