name: Prepare for release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
jobs:
  update-licenses:
    name: Update licenses
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run LicensePlist
      run: |
        ./Tools/license-plist \
          --output-path Aside/Settings.bundle \
          --force

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: Aside/Settings.bundle
        default_author: github_actions
